query myAccountVideos{
    myAccountVideos{
        profileImage{
            errors
            id
            moderation{
                approved
                invalids{
                    general
                    primary
                }
                recognized
            }
            shouldDestroy
            urls{
                blur
                middle
                original
                small
            }
        }
        videos{
            approved
            errors
            id
            invalids
            question{
                answerDurations{
                    full
                    min
                }
                audio{
                    duration
                    url
                }
                enabled
                id
                name
                topic
            }
            recognized
            screenUrl
            url
        }
        videosNumber
    }
}