query myFanbase($page: String){
    myFanbase(page: $page){
        age
        countLikes
        countMatches
        countSuperLikes
        currentLocation
        distance
        enabled
        firstName
        id
        image{
            approved
            blur
            errors
            id
            invalids
            middleUrl
            primary
            primaryInvalids
            recognized
            shouldDestroy
            smallUrl
            url
        }
        neighborhood
        premium
        profileImage{
            errors
            id
            moderation{
                approved
                invalids{
                    general
                    primary
                }
                recognized
            }
            shouldDestroy
            urls{
                blur
                middle
                original
                small
            }
        }
        userProfileId
        videos{
            approved
            errors
            id
            invalids
            question{
                answerDurations{
                    full
                    min
                }
                audio{
                    duration
                    url
                }
                enabled
                id
                name
                topic
            }
            recognized
            screenUrl
            url
        }
    }
}