query myPopularity{
    myPopularity{
        advertsInfo{
            countNewAdverts
            lastMessage
            photoModerationPassed
            videoModerationPassed
        }
        conversations{
            actual
            blocked
            chatExpired
            chatId
            countMessages
            expireAt
            haveSuperLike
            iRecovered
            isMyTurn
            lastMessage
            matchPhotoModerationPassed
            matchUser{
                age
                firstName
                id
                profilePhoto
                userProfileId
            }
            matchVideoModerationPassed
            recovered
            secondUserReconnect
            secondUserUnmatch
            sentSuperLike
            unreadMessagesCount
            userRecovered
        }
        intros{
            actual
            blocked
            chatExpired
            chatId
            countMessages
            expireAt
            haveSuperLike
            iRecovered
            isMyTurn
            lastMessage
            matchPhotoModerationPassed
            matchUser{
                age
                firstName
                id
                profilePhoto
                userProfileId
            }
            matchVideoModerationPassed
            recovered
            secondUserReconnect
            secondUserUnmatch
            sentSuperLike
            unreadMessagesCount
            userRecovered
        }
        likes{
            count
            lastSender{
                age
                firstName
                id
                profilePhoto
                userProfileId
            }
            photoModerationPassed
            videoModerationPassed
        }
        matches{
            actual
            blocked
            chatExpired
            chatId
            countMessages
            expireAt
            haveSuperLike
            iRecovered
            isMyTurn
            lastMessage
            matchPhotoModerationPassed
            matchUser{
                age
                firstName
                id
                profilePhoto
                userProfileId
            }
            matchVideoModerationPassed
            recovered
            secondUserReconnect
            secondUserUnmatch
            sentSuperLike
            unreadMessagesCount
            userRecovered
        }
    }
}