query search($page: String){
    search(page: $page){
        attitudeToAlcohol
        attitudeToKid{
            attitudeToKidId
            attitudeToKidName
            chosenKidsConditions{
                conditionId
                name
                value
            }
            kidsConditionList{
                checked
                conditionId
                name
                visible
            }
        }
        attitudeToMarijuana
        attitudeToPet
        attitudeToSmoking
        birthDate
        distance
        currentLocation
        educationLevel
        enabled
        firstName
        gender
        genderShort
        height
        id
        image{
            errors
            id
            moderation{
                approved
                invalids{
                    general
                    primary
                }
                recognized
            }
            shouldDestroy
            urls{
                blur
                middle
                original
                small
            }
        }
        job
        likeToMeet
        likedMe
        nameOfSchool
        nativeLanguage
        neighborhood
        photoModerationPassed
        physicalActivity
        placeOfBirth
        placeOfWork
        politicalIdeology
        profileImage{
            errors
            id
            moderation{
                approved
                recognized
            }
            shouldDestroy
            urls{
                blur
                middle
                original
                small
            }
        }
        relationshipGoal
        relationshipStatus
        religion
        superlikedMe
        userAccountId
        videoModerationPassed
        videos{
            approved
            errors
            id
            invalids
            question{
                answerDurations{
                    full
                    min
                }
                audio{
                    duration
                    url
                }
                enabled
                id
                name
                topic
            }
            recognized
            screenUrl
            url
        }
        zodiac
    }
}