query userGenders{
    userGenders{
        current{
            base{
                id
                name
                shortName
            }
            other{
                id
                name
                shortName
            }
            selected{
                id
                name
                shortName
            }
            visibility
        }
        likeToMeet{
            list{
                id
                name
            }
            selected{
                id
                name
            }
        }
    }
}