export default {
  AUDIO_FORMAT: 'YYYYMMDDHHmm',
  DAY_NAME_DD: 'dd',
  DAY_NAME_FORMAT: 'DD dddd',
  MONTH_LABEL: 'MMMM',
  MONTH_TITLE_DAY: 'D',
  PURCHASE_DATE_FORMAT: 'DD MMM YYYY',
  SERVER_DATE_FORMAT: 'YYYY-MM-DD',
  SERVER_TIME_FORMAT: 'HH:mm',
  SERVER_TIME_SECONDS_FORMAT: 'HH:mm:ss',
  WEEK_DAY: 'dddd',
};
