subscription updatedUserLikes($userAccountId: String!){
    updatedUserLikes(userAccountId: $userAccountId){
        count
        lastSender{
            age
            firstName
            id
            profilePhoto
            userProfileId
        }
        photoModerationPassed
        videoModerationPassed
    }
}